language: node_js
sudo: false
node_js:
  - '6.9.5'

cache:
  directories:
    - $HOME/.chrome/chromium

before_install:
  - ./scripts/install_chromium.sh
  - export LIGHTHOUSE_CHROMIUM_PATH=$HOME/.chrome/chromium/chrome-linux/chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - node index.js
  - node index.js
  - node index.js
  - node index.js
  - node index.js